/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerState = IDL.Record({
  'rebirthCount' : IDL.Int,
  'clickPower' : IDL.Int,
  'coins' : IDL.Int,
  'passiveRate' : IDL.Int,
  'rebirthBonus' : IDL.Int,
  'upgradesBought' : IDL.Vec(IDL.Text),
  'lastClaim' : IDL.Int,
});

export const idlService = IDL.Service({
  'buyUpgrade' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [IDL.Variant({ 'ok' : PlayerState, 'err' : IDL.Text })],
      [],
    ),
  'claimPassive' : IDL.Func([], [IDL.Int], []),
  'click' : IDL.Func([], [IDL.Int], []),
  'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
  'rebirth' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerState = IDL.Record({
    'rebirthCount' : IDL.Int,
    'clickPower' : IDL.Int,
    'coins' : IDL.Int,
    'passiveRate' : IDL.Int,
    'rebirthBonus' : IDL.Int,
    'upgradesBought' : IDL.Vec(IDL.Text),
    'lastClaim' : IDL.Int,
  });
  
  return IDL.Service({
    'buyUpgrade' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [IDL.Variant({ 'ok' : PlayerState, 'err' : IDL.Text })],
        [],
      ),
    'claimPassive' : IDL.Func([], [IDL.Int], []),
    'click' : IDL.Func([], [IDL.Int], []),
    'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
    'rebirth' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };